version: '3.9'
services:
    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5432:5432'
        volumes:
            - db:/var/lib/postgresql/data
        
    client:
        restart: always
        depends_on:
            - restapi
        image: manage-sys-client
        environment:
            CHOKIDAR_USEPOLLING: "true"
        build:
            context: ./client/
            dockerfile: Dockerfile
            args:
                - API_URL=http://192.53.123.78:8080/
        ports:
            - '443:443'
        links:
            - restapi
    restapi:
        restart: always
        image: manage-sys-server
        build:
            context: ./server/
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - '8080:8080'
        environment:
            - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
            - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
            - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
            - SPRING_JPA_DDL_MODE=${SPRING_JPA_DDL_MODE}
            - JWT_SECRET=${JWT_SECRET}
        links:
            - db
networks:
    manage.sys-network:
        internal: true
        driver: bridge
volumes:
    db:
        driver: local
