version: '3.9'
services:
    db:
        image: 'postgres:10'
        container_name: db
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=compose-postgres
            - POSTGRES_PASSWORD=compose-postgres
        networks:
            - manage.sys-network
    restapi:
        build:
            target: test
            context: ./server/
            dockerfile: Dockerfile
        ports:
            - '8080:8080'
        depends_on:
            - db

        networks:
            - manage.sys-network
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres?createDatabaseIfNotExist=true
            - SPRING_DATASOURCE_USERNAME=compose-postgres
            - SPRING_DATASOURCE_PASSWORD=compose-postgres
            - SPRING_JPA_DDL_MODE=create-drop
            - JWT_SECRET=jwttestingsecretkey12345

networks:
    manage.sys-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
        driver: local
