version: '3.9'
services:
    client:
        image: finalscriptcontainers.azurecr.io/manage-sys-client
        build:
            context: ./client/
            dockerfile: Dockerfile
        ports:
            - '443:443'
        depends_on:
            - restapi
        environment:
            - REACT_APP_API_URL=${REACT_APP_API_URL}
        networks:
            - manage.sys-network
    restapi:
        image: finalscriptcontainers.azurecr.io/manage-sys-api
        build:
            context: ./server/
            dockerfile: Dockerfile
        ports:
            - '80:8080'
        environment:
            - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
            - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
            - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
            - SPRING_JPA_DDL_MODE=${SPRING_JPA_DDL_MODE}
            - JWT_SECRET=${JWT_SECRET}
        networks:
            - manage.sys-network
networks:
    manage.sys-network:
