version: '3.9'
services:
    client:
        build:
            target: development
            context: ./client/
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        depends_on:
            - restapi
        environment:
            - CHOKIDAR_USEPOLLING=true
            - NODE_ENV=development
            - REACT_APP_API_URL=${REACT_APP_API_URL}
        networks:
            - manage.sys-network
        stdin_open: true
        tty: true
        volumes:
            - type: bind
              source: ./client
              target: /app
    restapi:
        build:
            target: development
            context: ./server/
            dockerfile: Dockerfile
        ports:
            - '8080:8080'
        environment:
            - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
            - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
            - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
            - SPRING_JPA_DDL_MODE=${SPRING_JPA_DDL_MODE}
            - JWT_SECRET=${JWT_SECRET}
        networks:
            - manage.sys-network
networks:
    manage.sys-network:
