version: '3.9'
services:
    client:
        image: finalscriptcontainers.azurecr.io/manage-sys-client
        build:
            context: ./client/
            dockerfile: Dockerfile
            args:
                - API_URL=${REACT_APP_API_URL}
        ports:
            - '443:3000'
        networks:
            - manage.sys-network
    restapi:
        image: finalscriptcontainers.azurecr.io/manage-sys-server
        build:
            target: production
            context: ./server/
            dockerfile: Dockerfile
        depends_on:
            - client
        environment:
            - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
            - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
            - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
            - SPRING_JPA_DDL_MODE=${SPRING_JPA_DDL_MODE}
            - JWT_SECRET=${JWT_SECRET}
        networks:
            - manage.sys-network

networks:
    manage.sys-network:
        internal: true
        driver: bridge
